version: '3.2'

services:
  comparador-api:    
    container_name: comparador-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: comparador

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always    
    ports:
      - "8082:8082"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 8082    
    depends_on:
      - postgres